version: '3'

services:
  ubuntu-development:
    container_name: ubuntu-development
    build:
      context: ubuntu
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /Users/richardfrancis/dev_containers/rf-workspace-ubuntu/data:/home