services:
  ubuntu-development:
    container_name: ubuntu-development
    build:
      context: docker/ubuntu
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    volumes:
      - /Users/richardfrancis/dev_containers/rf-workspace-ubuntu/data:/home